base_url = "https://www.geekrunners.com"
title = "Geek Runners"
description = "Everything that makes running cooler than it actually is"
default_language = "en"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "bbedit"

[extra]
# Put all your custom variables here
